### ISSUE TITLE
`swap_columns` and `swap_rows` are unsound

### ISSUE THREAD

**Issue by adamAndMath** [maplant/aljabar#20]
Both functions are built with the same structure and safety reasoning, so I'll focus on `swap_columns`.
```rust
pub fn swap_columns(&mut self, a: usize, b: usize) {
    let a: *mut MaybeUninit<Vector<T, { N }>> = unsafe { mem::transmute(&mut self.0[a]) };
    let b: *mut MaybeUninit<Vector<T, { N }>> = unsafe { mem::transmute(&mut self.0[b]) };
    // The following should return a MaybeUninit<T>, which will not be dropped.
    unsafe { a.replace(b.replace(a.replace(MaybeUninit::uninit()))) };
}
```
Take the case of calling `swap_columns` with `a=b`. This leads to code equivalent to
```rust
pub fn swap_columns(&mut self, a: usize) {
    let a: *mut MaybeUninit<Vector<T, { N }>> = unsafe { mem::transmute(&mut self.0[a]) };
    unsafe { a.replace(a.replace(a.replace(MaybeUninit::uninit()))) };
}
```
Going through the `replace` calls one by one. I'll refer to the parameter/return value as `tmp`.
```
a = val; tmp = uninit
a = uninit; tmp = val // first call
a = val; tmp = uninit // second call
a = uninit; tmp = val // third call
```
Thus the function would conclude `a` being uninitialised memory.

**Comment by maplant** [comment]
Thank you for spotting this! This is a really great find, and a pretty glaring error on my part. I have fixed this and bumped the minor version of aljabar to address it. 

I  hope that this didn't cause some confusing problems for you, because I can imagine it would be quite a nuisance to debug.

**Comment by adamAndMath** [comment]
I just looked through the code as the project seems interesting
