### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [maplant/aljabar#27]
Hey, I was passing by and I didn't see any examples. It would be pretty nice if you guys show what it can do so we can have an idea of it's capabilities without having to go town first. 🙂

**Comment by maplant** [comment]
Hi there, we put a few guided examples in the api documentation: https://docs.rs/al-jabr/0.1.0/al_jabr/
Are these insufficient, or did you expect them to be in the README?

**Comment by Gabriel-Alves-Cunha** [comment]
Hum, I see. They are sufficient. I guess just an info saying where to find the examples would be great. 😊

PS: Just a question: do you expect this library to grow in the future, or you're gonna keep it like it is, I'm just asking because there are libraries like Algebrite in javascript that has like "higher-language" purposes?

**Comment by maplant** [comment]
> 
> 
> Hum, I see. They are sufficient. I guess just an info saying where to find the examples would be great. 😊

Sure thing. As a quick, tip, at the top of most readme's for crates, there is a "doc" button that looks like this: 
[![Documentation](https://docs.rs/al-jabr/badge.svg)](https://docs.rs/al-jabr)
This will link you to the documentation for the crate. 

> 
> PS: Just a question: do you expect this library to grow in the future, or you're gonna keep it like it is, I'm just asking because there are libraries like Algebrite in javascript that has like "higher-language" purposes?

We do intend to continue to add features to al-jabr. If there is a feature you think we missed, feel free to add an issue , and we will implement it for you.
