### ISSUE TITLE
Type-enforced row/column majorness?

### ISSUE THREAD

**Issue by EkardNT** [maplant/aljabar#5]
Have you considered raising the row/column majorness of vectors and matrices to the type level? I was thinking about how aljabar hardcodes matrices as column-major, and was wondering about 0-overhead ways of supporting whichever the user chooses (so, not using an enum or flag discriminant at runtime).

I've put a sketch of what the type definitions might look like in the cunningly-named aljabr repo [here](https://github.com/EkardNT/aljabr/blob/master/src/lib.rs#L6-L35).

The important bits are:
```rust
/// Marker for a row-major matrix.
pub struct RowM;
/// Marker for a column-major matrix.
pub struct ColM;
/// Marker for a row vector.
pub struct RowV;
/// Marker for a column vector.
pub struct ColV;

pub struct Vector<T: Copy, M, const N: usize> {
    _major: PhantomData<M>,
    elements: [T; N]
}

pub struct Matrix<T: Copy, M, const Major: usize, const Minor: usize> {
    _major: PhantomData<M>,
    elements: [[T; Minor]; Major]
}
```

In this example, Vector's M parameter would be either RowV or ColV and Matrix's M parameter would be either RowM or ColM.

I'm not convinced this is actually a good idea yet, but its seemed interesting so far.

**Comment by maplant** [comment]
It's an interesting idea but ultimately I'm not too sure there's any real demand for this. Plus, we couldn't change this until 1.0 anyway as I'm vaguely trying to adhere to semver.

**Comment by EkardNT** [comment]
Yeah it was just an idle thought I had, probably not worth dealing with interface changes. I may or more realistically may not continue toying with it on the side.
