### ISSUE TITLE
Higher-dimensional tensors

### ISSUE THREAD

**Issue by vadixidav** [maplant/aljabar#8]
I notice that you have vectors and matrices. Would you be willing to accept PRs adding a few more dimensions? We can leave Vector and Matrix and make them aliases of something like `Tensor1` and `Tensor2`. Then we can start to add operations like higher-dimensional convolution and such.

If this is outside the scope of `aljabar`, I don't mind creating a new crate, but I figure this is a good place for collective const generics experimentation on linear algebra, so I wanted to see if this is of interest.

**Comment by maplant** [comment]
PR acceptance is pretty ad-hoc at the moment but I will say that any addition that is backwards compatible (I.e. passing existing tests) and provides such generality as described I think makes an extremely strong case for being accepted. At the very least, I would love to see whatever you come up with, whether it manifests as a PR here or in a separate crate

**Comment by maplant** [comment]
I'm going to close this issue because I do not believe that this dimensionality is expressible with const generics in rust at the current moment
