### ISSUE TITLE
Is a license of GPL3 too restrictive?

### ISSUE THREAD

**Issue by maplant** [maplant/aljabar#9]
While I would urge reconsideration of any use of this library in production code, I am aware that a GPL3 license can be a bit too restrictive. If someone would prefer a different license I would be happy to switch to that

**Comment by bjorn3** [comment]
Most rust crates are dual licensed as MIT and Apache 2.0.

**Comment by maplant** [comment]
Yes, that seems to be the case. I’m fine with changing it to that in the next release. @EkardNT you are the other contributor, are you ok with that change?

**Comment by EkardNT** [comment]
Certainly, I have no objection to such a license change.

**Comment by maplant** [comment]
Then it will be changed in the next release

**Comment by maplant** [comment]
Changed!
